[package]
name = "shouji"
version = "0.0.1"
authors = ["Joseph Kordish <joe@unicornclouds.com>"]

[dependencies]
#clippy = "*"
docopt = "*"
rustc-serialize = "*"
curl = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"
