[package]
name = "shouji"
version = "0.1.0"
authors = ["Joseph Kordish <joe@unicornclouds.com>"]

[dependencies]
docopt = "*"
rustc-serialize = "*"
curl = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"
