[package]
name = "shouji"
version = "0.2.1"
authors = ["Joseph Kordish <joe@unicornclouds.com>"]

[dependencies]
docopt = "*"
docopt_macros = "*"
rustc-serialize = "*"
curl = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"
